import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ApiErrorService } from '../../core/services/api-error.service';
import { ToastService } from '../../core/services/toast.service';
import { authStyles } from './auth-layout.styles';
@Component({selector:'app-login',standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<div class="auth-page"><section class="auth-art"><div class="auth-brand"><div class="auth-logo">C</div><div><strong>Campus Services</strong><span>One portal. Every campus service.</span></div></div><div class="auth-copy"><span style="color:#c4b5fd;font-size:.78rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase">University life, simplified</span><h1>Everything you need, in one secure campus portal.</h1><p>Apply for hostels, reserve labs, register for events, raise complaints, request certificates, pay fees and track every update from a single dashboard.</p></div><div class="auth-features"><span class="auth-chip">Secure access</span><span class="auth-chip">Mobile friendly</span><span class="auth-chip">Live status updates</span></div></section>
<section class="auth-main"><form class="auth-card" #f="ngForm" (ngSubmit)="submit()"><h2>Welcome back</h2><p>Sign in with your campus account to continue.</p>@if(error){<div class="alert error" style="margin-bottom:16px">{{error}}</div>}<div class="stack"><div class="field"><label for="email">Email address</label><input class="input" id="email" name="email" type="email" required email autocomplete="email" [(ngModel)]="email" placeholder="name@university.edu"></div><div class="field"><label for="password">Password</label><div class="password-wrap"><input class="input" id="password" name="password" [type]="showPassword?'text':'password'" required autocomplete="current-password" [(ngModel)]="password" placeholder="Enter your password"><button type="button" class="password-toggle" (click)="showPassword=!showPassword">{{showPassword?'Hide':'Show'}}</button></div></div><div class="checks"><span class="small muted">Secure session</span><a class="auth-link" routerLink="/forgot-password">Forgot password?</a></div><button class="btn btn-primary" [disabled]="f.invalid||loading">{{loading?'Signing in…':'Sign in'}}</button></div><div class="auth-footer">New student? <a class="auth-link" routerLink="/register">Create your account</a></div></form></section></div>`,styles:[authStyles]})
export class LoginComponent{email='';password='';showPassword=false;loading=false;error='';constructor(private auth:AuthService,private router:Router,private errors:ApiErrorService,private toast:ToastService){}submit(){this.loading=true;this.error='';this.auth.login(this.email.trim(),this.password).subscribe({next:()=>{this.loading=false;this.toast.success('Signed in successfully.');void this.router.navigate(['/dashboard']);},error:e=>{this.loading=false;this.error=this.errors.message(e,'Unable to sign in.')}})}}
