import { ChangeDetectorRef, Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, NgForm } from '@angular/forms';
import { StudentService } from '../../core/services/student.service';
import { AdminAccount, Faculty, StudentListItem, StudentMaster } from '../../core/models/domain.models';
import { StatusBadgeComponent } from '../../shared/components/status-badge.component';
import { ApiErrorService } from '../../core/services/api-error.service';
import { ToastService } from '../../core/services/toast.service';

@Component({selector:'app-students-admin',standalone:true,imports:[CommonModule,FormsModule,StatusBadgeComponent],template:`
<div class="page"><div class="page-head"><div><h1>Student administration</h1><p>Manage registered students, student-master records, faculties and administrator accounts.</p></div></div>
<div class="tabs"><button class="tab" [class.active]="tab==='students'" (click)="tab='students';loadStudents()">Students</button><button class="tab" [class.active]="tab==='master'" (click)="tab='master';loadMaster()">Student master</button><button class="tab" [class.active]="tab==='faculties'" (click)="tab='faculties';loadFaculties()">Faculties</button><button class="tab" [class.active]="tab==='admins'" (click)="tab='admins';loadAdmins()">Admin accounts</button></div>
@if(tab==='students'){<div class="card"><div class="toolbar"><div class="field search"><label>Search students</label><input class="input" [(ngModel)]="studentSearch" (keyup.enter)="loadStudents()" placeholder="Name, index or email"></div><div class="field"><label>Faculty</label><select class="select" [(ngModel)]="studentFaculty"><option [ngValue]="null">All faculties</option>@for(f of faculties;track f.facultyId){<option [ngValue]="f.facultyId">{{f.code}}</option>}</select></div><button class="btn btn-primary" (click)="loadStudents()">Search</button></div>@if(students.length){<div class="table-wrap"><table class="table"><thead><tr><th>Index</th><th>Student</th><th>Faculty</th><th>Status</th><th></th></tr></thead><tbody>@for(s of students;track s.studentId){<tr><td class="mono">{{s.indexNumber}}</td><td><strong>{{s.fullName}}</strong><div class="small muted">{{s.email}}</div></td><td>{{s.facultyCode}}</td><td><app-status-badge [value]="s.isActive?'Active':'Inactive'"/></td><td class="right"><div class="row" style="justify-content:flex-end"><button class="btn btn-secondary btn-sm" (click)="editStudent(s)">Edit</button>@if(s.isActive){<button class="btn btn-danger btn-sm" (click)="deactivateStudent(s)">Deactivate</button>}@else{<button class="btn btn-success btn-sm" (click)="reactivateStudent(s)">Reactivate</button>}</div></td></tr>}</tbody></table></div><div class="row between" style="margin-top:14px"><span class="small muted">{{studentTotal}} students</span><div class="row"><button class="btn btn-secondary btn-sm" [disabled]="studentPage<=1" (click)="previousStudentPage()">Previous</button><span class="small">Page {{studentPage}}</span><button class="btn btn-secondary btn-sm" [disabled]="students.length<20" (click)="nextStudentPage()">Next</button></div></div>}@else{<div class="empty">No students matched the current filters.</div>}</div>}
@if(tab==='master'){<div class="card"><div class="row between mobile-stack"><div><h3 class="card-title">Student master list</h3><div class="card-sub">Pre-approved university identity records used during registration.</div></div><div class="row mobile-stack"><label class="btn btn-secondary"><input type="file" accept=".csv,text/csv" hidden (change)="importCsv($event)">Import CSV</label><button class="btn btn-primary" (click)="newMaster()">Add record</button></div></div><div class="toolbar" style="margin-top:18px"><div class="field search"><label>Search</label><input class="input" [(ngModel)]="masterSearch" (keyup.enter)="loadMaster()" placeholder="Index or name"></div><button class="btn btn-secondary" (click)="loadMaster()">Filter</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Index</th><th>Name</th><th>Faculty</th><th>Intake</th><th>Registered</th><th>Status</th><th></th></tr></thead><tbody>@for(m of master;track m.studentMasterId){<tr><td class="mono">{{m.indexNumber}}</td><td><strong>{{m.fullName}}</strong><div class="small muted">{{m.officialEmail||'No official email'}}</div></td><td>{{m.facultyCode}}</td><td>{{m.intakeYear}}</td><td>{{m.alreadyRegistered?'Yes':'No'}}</td><td><app-status-badge [value]="m.isActive?'Active':'Inactive'"/></td><td class="right"><div class="row" style="justify-content:flex-end"><button class="btn btn-secondary btn-sm" (click)="editMaster(m)">Edit</button><button class="btn btn-danger btn-sm" (click)="deleteMaster(m)" [attr.aria-label]="'Delete '+m.indexNumber">Delete</button></div></td></tr>}</tbody></table></div></div>}
@if(tab==='faculties'){<div class="grid grid-3"><div class="card" style="grid-column:span 1"><h3 class="card-title">{{facultyEditId?'Edit':'Add'}} faculty</h3><form class="stack" #ff="ngForm" (ngSubmit)="saveFaculty()" style="margin-top:16px"><div class="field"><label>Code</label><input class="input" required maxlength="30" name="code" [(ngModel)]="facultyForm.code"></div><div class="field"><label>Name</label><input class="input" required maxlength="150" name="name" [(ngModel)]="facultyForm.name"></div>@if(facultyEditId){<label class="row"><input type="checkbox" name="active" [(ngModel)]="facultyForm.isActive"> Active</label>}<div class="row"><button class="btn btn-primary" [disabled]="ff.invalid">Save</button>@if(facultyEditId){<button type="button" class="btn btn-secondary" (click)="resetFaculty()">Cancel</button>}</div></form></div><div class="card" style="grid-column:span 2"><h3 class="card-title">Faculties</h3><div class="divider"></div><div class="table-wrap"><table class="table"><thead><tr><th>Code</th><th>Name</th><th>Status</th><th></th></tr></thead><tbody>@for(f of faculties;track f.facultyId){<tr><td><strong>{{f.code}}</strong></td><td>{{f.name}}</td><td><app-status-badge [value]="f.isActive?'Active':'Inactive'"/></td><td class="right"><div class="row" style="justify-content:flex-end"><button class="btn btn-secondary btn-sm" (click)="editFaculty(f)">Edit</button><button class="btn btn-danger btn-sm" (click)="deleteFaculty(f)">Delete</button></div></td></tr>}</tbody></table></div></div></div>}
@if(tab==='admins'){<div class="grid grid-3"><div class="card"><h3 class="card-title">Create administrator</h3><form class="stack" #af="ngForm" (ngSubmit)="createAdmin()" style="margin-top:16px"><div class="field"><label>Email</label><input class="input" type="email" email required name="email" [(ngModel)]="adminEmail"></div><div class="field"><label>Temporary password</label><input class="input" type="password" minlength="8" required name="password" [(ngModel)]="adminPassword"></div><button class="btn btn-primary" [disabled]="af.invalid">Create admin</button></form></div><div class="card" style="grid-column:span 2"><h3 class="card-title">Administrator accounts</h3><div class="divider"></div><div class="table-wrap"><table class="table"><thead><tr><th>Email</th><th>Verified</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>@for(a of admins;track a.userId){<tr><td><strong>{{a.email}}</strong></td><td>{{a.emailVerified?'Yes':'No'}}</td><td><app-status-badge [value]="a.isActive?'Active':'Inactive'"/></td><td>{{a.createdAt|date:'mediumDate'}}</td><td class="right">@if(a.isActive){<button class="btn btn-danger btn-sm" (click)="toggleAdmin(a,false)">Deactivate</button>}@else{<button class="btn btn-success btn-sm" (click)="toggleAdmin(a,true)">Reactivate</button>}</td></tr>}</tbody></table></div></div></div>}
@if(studentEdit){<div class="modal-backdrop" (click)="studentEdit=null"><div class="modal" (click)="$event.stopPropagation()"><div class="modal-head"><div><h2>Edit student</h2><div class="small muted">{{studentEdit.indexNumber}}</div></div><button class="icon-btn" (click)="studentEdit=null">×</button></div><form class="form-grid" #sf="ngForm" (ngSubmit)="saveStudent()"><div class="field full"><label>Full name</label><input class="input" name="name" required [(ngModel)]="studentForm.fullName"></div><div class="field"><label>Email</label><input class="input" type="email" email required name="email" [(ngModel)]="studentForm.email"></div><div class="field"><label>Faculty</label><select class="select" name="faculty" required [(ngModel)]="studentForm.facultyId">@for(f of faculties;track f.facultyId){<option [ngValue]="f.facultyId">{{f.code}} · {{f.name}}</option>}</select></div><div class="field"><label>Phone</label><input class="input" name="phone" [(ngModel)]="studentForm.phoneNumber"></div><div class="field full"><label>Address</label><textarea class="textarea" name="address" [(ngModel)]="studentForm.address"></textarea></div><div class="row"><button class="btn btn-primary" [disabled]="sf.invalid">Save changes</button><button type="button" class="btn btn-secondary" (click)="studentEdit=null">Cancel</button></div></form></div></div>}
@if(masterModal){<div class="modal-backdrop" (click)="masterModal=false"><div class="modal" (click)="$event.stopPropagation()"><div class="modal-head"><h2>{{masterEditId?'Edit':'Create'}} master record</h2><button class="icon-btn" [disabled]="savingMaster" (click)="masterModal=false">×</button></div><form class="form-grid" #mf="ngForm" (ngSubmit)="saveMaster()"><div class="field"><label>Index number</label><input class="input" required name="idx" [(ngModel)]="masterForm.indexNumber"></div><div class="field"><label>Full name</label><input class="input" required name="full" [(ngModel)]="masterForm.fullName"></div><div class="field"><label>Official email</label><input class="input" email name="official" [(ngModel)]="masterForm.officialEmail"></div><div class="field"><label>Faculty</label><select class="select" required name="fac" [(ngModel)]="masterForm.facultyId">@for(f of faculties;track f.facultyId){<option [ngValue]="f.facultyId">{{f.code}}</option>}</select></div><div class="field"><label>Intake year</label><input class="input" type="number" min="2000" max="2100" required name="year" [(ngModel)]="masterForm.intakeYear"></div><div class="field"><label class="row" style="margin-top:26px"><input type="checkbox" name="active" [(ngModel)]="masterForm.isActive"> Active</label></div><div class="row"><button class="btn btn-primary" [disabled]="mf.invalid||savingMaster">{{savingMaster?'Saving…':'Save record'}}</button><button type="button" class="btn btn-secondary" [disabled]="savingMaster" (click)="masterModal=false">Cancel</button></div></form></div></div>}
</div>`})
export class StudentsAdminComponent implements OnInit{
 @ViewChild('ff') private facultyNgForm?:NgForm;
 savingFaculty=false;
 tab:'students'|'master'|'faculties'|'admins'='students';students:StudentListItem[]=[];faculties:Faculty[]=[];master:StudentMaster[]=[];admins:AdminAccount[]=[];studentSearch='';studentFaculty:number|null=null;studentPage=1;studentTotal=0;masterSearch='';studentEdit:StudentListItem|null=null;studentForm:any={};masterModal=false;masterEditId:number|null=null;savingMaster=false;masterForm:any={};facultyEditId:number|null=null;facultyForm:any={code:'',name:'',isActive:true};adminEmail='';adminPassword='';
 constructor(private service:StudentService,private errors:ApiErrorService,private toast:ToastService,private cdr:ChangeDetectorRef){}
 ngOnInit(){this.loadFaculties();this.loadStudents()}
 previousStudentPage(){if(this.studentPage<=1)return;this.studentPage-=1;this.loadStudents()}
 nextStudentPage(){if(this.students.length<20)return;this.studentPage+=1;this.loadStudents()}
 loadStudents(){this.service.search(this.studentSearch,this.studentFaculty||undefined,this.studentPage).subscribe({next:r=>{this.students=r.items;this.studentTotal=r.totalCount},error:e=>this.toast.error(this.errors.message(e))})}
 editStudent(s:StudentListItem){this.service.get(s.studentId).subscribe({next:r=>{const p=r.data?.profile??r.data??s;this.studentEdit=s;this.studentForm={email:p.email,fullName:p.fullName,facultyId:p.facultyId,phoneNumber:p.phoneNumber||'',address:p.address||''}},error:e=>this.toast.error(this.errors.message(e))})}
 saveStudent(){if(!this.studentEdit)return;this.service.adminUpdate(this.studentEdit.studentId,this.studentForm).subscribe({next:()=>{this.toast.success('Student updated.');this.studentEdit=null;this.loadStudents()},error:e=>this.toast.error(this.errors.message(e))})}
 deactivateStudent(s:StudentListItem){this.service.deactivationCheck(s.studentId).subscribe({next:c=>{if(!c.canDeactivate){this.toast.warning(`Cannot deactivate: ${c.blockingCommitments.join(', ')}`);return}if(confirm(`Deactivate ${s.fullName}?`))this.service.deactivate(s.studentId).subscribe({next:()=>{this.toast.success('Student deactivated.');this.loadStudents()},error:e=>this.toast.error(this.errors.message(e))})},error:e=>this.toast.error(this.errors.message(e))})}
 reactivateStudent(s:StudentListItem){this.service.reactivate(s.studentId).subscribe({next:()=>{this.toast.success('Student reactivated.');this.loadStudents()},error:e=>this.toast.error(this.errors.message(e))})}
 loadFaculties(){this.service.faculties().subscribe({next:x=>{this.faculties=this.sortFaculties(x);this.cdr.markForCheck()},error:e=>this.toast.error(this.errors.message(e))})}
 editFaculty(f:Faculty){this.facultyEditId=f.facultyId;this.facultyForm={code:f.code,name:f.name,isActive:f.isActive}}
 resetFaculty(){this.facultyEditId=null;this.facultyForm={code:'',name:'',isActive:true};this.facultyNgForm?.resetForm(this.facultyForm)}
 saveFaculty(){
  if(this.savingFaculty)return;
  const editId=this.facultyEditId;
  const payload={code:String(this.facultyForm.code).trim(),name:String(this.facultyForm.name).trim(),isActive:this.facultyForm.isActive};
  this.savingFaculty=true;
  const request=editId!==null?this.service.updateFaculty(editId,payload):this.service.createFaculty({code:payload.code,name:payload.name});
  request.subscribe({
   next:saved=>{
    this.faculties=this.sortFaculties(editId!==null?this.faculties.map(f=>f.facultyId===editId?saved:f):[...this.faculties.filter(f=>f.facultyId!==saved.facultyId),saved]);
    this.savingFaculty=false;
    this.resetFaculty();
    this.toast.success('Faculty saved.');
    this.cdr.markForCheck();
   },
   error:e=>{this.savingFaculty=false;this.toast.error(this.errors.message(e));this.cdr.markForCheck()}
  })
 }
 deleteFaculty(f:Faculty){if(!confirm(`Delete ${f.code}?`))return;this.service.deleteFaculty(f.facultyId).subscribe({next:()=>{this.toast.success('Faculty deleted.');this.loadFaculties()},error:e=>this.toast.error(this.errors.message(e))})}
 private sortFaculties(faculties:Faculty[]):Faculty[]{return [...faculties].sort((left,right)=>left.code.localeCompare(right.code))}
 loadMaster(){this.service.masterSearch(this.masterSearch,undefined,1).subscribe({next:r=>{this.master=this.sortMasterRecords(r.items);this.cdr.markForCheck()},error:e=>this.toast.error(this.errors.message(e))})}newMaster(){this.masterEditId=null;this.masterForm={indexNumber:'',fullName:'',officialEmail:'',facultyId:this.faculties[0]?.facultyId||null,intakeYear:new Date().getFullYear(),isActive:true};this.masterModal=true}editMaster(m:StudentMaster){this.masterEditId=m.studentMasterId;this.masterForm={indexNumber:m.indexNumber,fullName:m.fullName,officialEmail:m.officialEmail||'',facultyId:m.facultyId,intakeYear:m.intakeYear,isActive:m.isActive};this.masterModal=true}saveMaster(){if(this.savingMaster)return;const editId=this.masterEditId;const b={...this.masterForm,indexNumber:String(this.masterForm.indexNumber).trim(),fullName:String(this.masterForm.fullName).trim(),officialEmail:String(this.masterForm.officialEmail||'').trim()||null};this.savingMaster=true;const req=editId!==null?this.service.updateMaster(editId,b):this.service.createMaster(b);req.subscribe({next:saved=>{this.master=this.sortMasterRecords(editId!==null?this.master.map(record=>record.studentMasterId===editId?saved:record):[...this.master.filter(record=>record.studentMasterId!==saved.studentMasterId),saved]);this.savingMaster=false;this.masterModal=false;this.masterEditId=null;this.toast.success('Student master record saved.');this.cdr.markForCheck()},error:e=>{this.savingMaster=false;this.toast.error(this.errors.message(e));this.cdr.markForCheck()}})}deleteMaster(m:StudentMaster){if(!confirm(`Permanently delete master record ${m.indexNumber}? This cannot be undone.`))return;this.service.deleteMaster(m.studentMasterId).subscribe({next:()=>{this.master=this.master.filter(record=>record.studentMasterId!==m.studentMasterId);this.toast.success('Master record permanently deleted.');this.cdr.markForCheck()},error:e=>{this.toast.error(this.errors.message(e));this.cdr.markForCheck()}})}importCsv(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;this.service.importMaster(file).subscribe({next:r=>{this.toast.success(`CSV imported: ${r.inserted} inserted, ${r.updated} updated.`);this.loadMaster()},error:er=>this.toast.error(this.errors.message(er))})}private sortMasterRecords(records:StudentMaster[]){return [...records].sort((left,right)=>left.indexNumber.localeCompare(right.indexNumber))}
 loadAdmins(){this.service.admins().subscribe({next:x=>this.admins=x,error:e=>this.toast.error(this.errors.message(e))})}createAdmin(){this.service.createAdmin({email:this.adminEmail,password:this.adminPassword}).subscribe({next:()=>{this.adminEmail='';this.adminPassword='';this.toast.success('Administrator created.');this.loadAdmins()},error:e=>this.toast.error(this.errors.message(e))})}toggleAdmin(a:AdminAccount,active:boolean){const req=active?this.service.reactivateAdmin(a.userId):this.service.deactivateAdmin(a.userId);req.subscribe({next:()=>{this.toast.success(`Administrator ${active?'reactivated':'deactivated'}.`);this.loadAdmins()},error:e=>this.toast.error(this.errors.message(e))})}
}
