import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HostelService } from '../../data-access/hostel.service';
import { AuthService } from '../../../../core/auth/services/auth.service';
import { Hostel, HostelApplication, HostelAvailability } from '../../models/hostel.models';
import { StatusBadgeComponent } from '../../../../shared/components/status-badge.component';
import { EmptyStateComponent } from '../../../../shared/components/empty-state.component';
import { LoadingComponent } from '../../../../shared/components/loading.component';
import { ApiErrorService } from '../../../../core/http/api-error.service';
import { ToastService } from '../../../../core/services/toast.service';
@Component({selector:'app-hostels',standalone:true,imports:[CommonModule,FormsModule,StatusBadgeComponent,EmptyStateComponent,LoadingComponent],template:`
<div class="page"><div class="page-head"><div><h1>Hostel accommodation</h1><p>Apply for a hostel, check capacity and track approval or room assignment.</p></div><button class="btn btn-primary" (click)="showForm=!showForm">{{showForm?'Close form':'New application'}}</button></div>
@if(showForm){<div class="card" style="margin-bottom:18px"><div class="row between"><div><h3 class="card-title">New hostel application</h3><div class="card-sub">Choose your preferred hostel and academic period.</div></div></div><form class="form-grid" #f="ngForm" (ngSubmit)="apply()" style="margin-top:18px"><div class="field"><label>Preferred hostel</label><select class="select" required name="hostel" [(ngModel)]="preferredHostelId" (ngModelChange)="loadAvailability()"><option [ngValue]="null">Select hostel</option>@for(h of hostels;track h.hostelId){<option [ngValue]="h.hostelId">{{h.name}} · {{h.location||'Campus'}}</option>}</select></div><div class="field"><label>Academic year</label><input class="input" required name="year" [(ngModel)]="academicYear" placeholder="2026/2027" (ngModelChange)="loadAvailability()"></div><div class="field"><label>Semester</label><select class="select" required name="sem" [(ngModel)]="semester" (ngModelChange)="loadAvailability()"><option value="Semester 1">Semester 1</option><option value="Semester 2">Semester 2</option></select></div><div class="field full"><label>Special requirements</label><textarea class="textarea" name="requirements" [(ngModel)]="specialRequirements" placeholder="Optional accessibility, medical or other accommodation notes"></textarea></div>@if(availability){<div class="field full"><div class="alert info"><strong>{{availability.available}} spaces available</strong> out of {{availability.totalCapacity}} total for {{availability.academicYear}} · {{availability.semester}}.</div></div>}<div><button class="btn btn-primary" [disabled]="f.invalid||submitting">{{submitting?'Submitting…':'Submit application'}}</button></div></form></div>}
@if(loading){<app-loading/>}@else if(error){<div class="alert error">{{error}}</div>}@else{<div class="grid grid-3" style="margin-bottom:18px">@for(h of hostels;track h.hostelId){<div class="card"><div class="row between"><div><div class="card-title">{{h.name}}</div><div class="card-sub">{{h.location||'University campus'}}</div></div><span class="badge success">Open</span></div><div class="divider"></div><div class="small muted">Select this hostel in the application form to see live academic-period capacity.</div></div>}</div><div class="card"><div class="row between"><div><h3 class="card-title">My applications</h3><div class="card-sub">Newest applications and decisions</div></div><button class="btn btn-secondary btn-sm" (click)="load()">Refresh</button></div><div class="divider"></div>@if(applications.length){<div class="table-wrap"><table class="table"><thead><tr><th>Hostel</th><th>Period</th><th>Status</th><th>Room</th><th>Requested</th><th></th></tr></thead><tbody>@for(a of applications;track a.hostelApplicationId){<tr><td><strong>{{a.preferredHostelName||('Hostel #'+a.preferredHostelId)}}</strong></td><td>{{a.academicYear}}<div class="small muted">{{a.semester}}</div></td><td><app-status-badge [value]="a.status"/></td><td>{{a.assignedRoomNumber||'—'}}</td><td>{{a.requestedAt|date:'mediumDate'}}</td><td class="right">@if(a.status==='Pending'){<button class="btn btn-danger btn-sm" (click)="cancel(a)">Cancel</button>}</td></tr>}</tbody></table></div>}@else{<app-empty-state icon="⌂" title="No hostel applications" message="Start a new application when accommodation is required."/>}</div>}</div>`})
export class HostelsComponent implements OnInit{hostels:Hostel[]=[];applications:HostelApplication[]=[];availability:HostelAvailability|null=null;loading=true;error='';showForm=false;submitting=false;preferredHostelId:number|null=null;academicYear=`${new Date().getFullYear()}/${new Date().getFullYear()+1}`;semester='Semester 1';specialRequirements='';constructor(private service:HostelService,private auth:AuthService,private errors:ApiErrorService,private toast:ToastService,private cdr:ChangeDetectorRef){}ngOnInit(){this.load()}load(){this.loading=true;this.error='';this.service.hostels().subscribe({next:x=>{this.hostels=x.filter(h=>h.isActive);this.loading=false;this.cdr.markForCheck()},error:e=>{this.error=this.errors.message(e);this.loading=false;this.cdr.markForCheck()}});this.service.mine().subscribe({next:x=>{this.applications=x;this.cdr.markForCheck()},error:e=>{this.toast.error(this.errors.message(e));this.cdr.markForCheck()}})}loadAvailability(){if(!this.preferredHostelId||!this.academicYear||!this.semester){this.availability=null;this.cdr.markForCheck();return}this.service.availability(this.preferredHostelId,this.academicYear,this.semester).subscribe({next:x=>{this.availability=x;this.cdr.markForCheck()},error:()=>{this.availability=null;this.cdr.markForCheck()}})}apply(){if(!this.preferredHostelId)return;this.submitting=true;this.service.apply({studentId:this.auth.studentId()||0,preferredHostelId:this.preferredHostelId,academicYear:this.academicYear,semester:this.semester,specialRequirements:this.specialRequirements||null}).subscribe({next:()=>{this.submitting=false;this.showForm=false;this.specialRequirements='';this.availability=null;this.toast.success('Hostel application submitted.');this.load()},error:e=>{this.submitting=false;this.toast.error(this.errors.message(e));this.cdr.markForCheck()}})}cancel(a:HostelApplication){if(!confirm('Cancel this hostel application?'))return;this.service.cancel(a.hostelApplicationId).subscribe({next:()=>{this.toast.success('Application cancelled.');this.load()},error:e=>{this.toast.error(this.errors.message(e));this.cdr.markForCheck()}})}}
