import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LabService } from '../../data-access/lab.service';
import { Lab, LabBooking, LabSeat, LabSlot } from '../../models/lab.models';
import { StatusBadgeComponent } from '../../../../shared/components/status-badge.component';
import { ApiErrorService } from '../../../../core/http/api-error.service';
import { ToastService } from '../../../../core/services/toast.service';

@Component({
  selector: 'app-labs-admin', standalone: true, imports: [CommonModule, FormsModule, StatusBadgeComponent],
  template: `
    <div class="page"><div class="page-head"><div><h1>Lab administration</h1><p>Manage labs, seats and time slots, and monitor all student reservations.</p></div></div>
      <div class="tabs"><button class="tab" [class.active]="tab==='labs'" (click)="tab='labs'">Labs & availability</button><button class="tab" [class.active]="tab==='bookings'" (click)="tab='bookings';loadBookings()">Bookings</button></div>

      @if (tab === 'labs') {
        <div class="grid grid-3"><div class="card"><h3 class="card-title">{{labEditId ? 'Edit' : 'Create'}} lab</h3><form class="stack" #labFormRef="ngForm" (ngSubmit)="saveLab()" style="margin-top:16px"><div class="field"><label>Code</label><input class="input" required name="code" [(ngModel)]="labForm.code"></div><div class="field"><label>Name</label><input class="input" required name="name" [(ngModel)]="labForm.name"></div><div class="field"><label>Type</label><select class="select" required name="type" [(ngModel)]="labForm.labType"><option>Computer</option><option>Science</option></select></div><div class="field"><label>Capacity</label><input class="input" type="number" min="1" required name="capacity" [(ngModel)]="labForm.capacity"></div>@if (labEditId) {<label class="row"><input type="checkbox" name="active" [(ngModel)]="labForm.isActive"> Active</label>}<div class="row"><button class="btn btn-primary" [disabled]="labFormRef.invalid">Save</button>@if (labEditId) {<button type="button" class="btn btn-secondary" (click)="resetLab()">Cancel</button>}</div></form></div>
          <div class="card" style="grid-column:span 2"><h3 class="card-title">Labs</h3><div class="card-sub">Select a lab to manage seats and inspect date-specific slot availability.</div><div class="divider"></div><div class="stack">@for (lab of labs; track lab.labId) {<div class="card flat" [style.background]="selectedLab?.labId === lab.labId ? '#eef2ff' : '#f8fafc'" (click)="selectLab(lab)" style="cursor:pointer"><div class="row between"><div><strong>{{lab.code}} · {{lab.name}}</strong><div class="small muted">{{lab.labType}} · capacity {{lab.capacity}}</div></div><div class="row"><app-status-badge [value]="lab.isActive ? 'Active' : 'Inactive'"/><button class="btn btn-secondary btn-sm" (click)="$event.stopPropagation();editLab(lab)">Edit</button><button class="btn btn-danger btn-sm" (click)="$event.stopPropagation();deleteLab(lab)">Delete</button></div></div></div>}</div></div></div>
        @if (selectedLab) {<div class="grid grid-2" style="margin-top:18px"><div class="card"><div class="row between"><div><h3 class="card-title">Seats · {{selectedLab.name}}</h3><div class="card-sub">Physical seat identifiers.</div></div><button class="btn btn-primary btn-sm" (click)="newSeat()">Add seat</button></div><div class="divider"></div><div class="row wrap">@for (seat of seats; track seat.labSeatId) {<div class="row" style="padding:8px 10px;background:#f8fafc;border-radius:10px"><strong>{{seat.seatNumber}}</strong><app-status-badge [value]="seat.isActive ? 'Active' : 'Inactive'"/><button class="btn btn-secondary btn-sm" (click)="editSeat(seat)">Edit</button><button class="btn btn-danger btn-sm" (click)="deleteSeat(seat)">Delete</button></div>}@if (!seats.length) {<span class="muted small">No seats configured.</span>}</div></div><div class="card"><div class="row between"><div><h3 class="card-title">Time slots</h3><div class="card-sub">Inspect available slots for a date.</div></div><button class="btn btn-primary btn-sm" (click)="newSlot()">Add slot</button></div><div class="field" style="max-width:230px;margin:16px 0"><label>Inspect date</label><input class="input" type="date" [(ngModel)]="slotDate" (ngModelChange)="loadSlots()"></div><div class="stack">@for (slot of slots; track slot.labTimeSlotId) {<div class="row between" style="padding:10px;background:#f8fafc;border-radius:10px"><div><strong>{{slot.startTime}}–{{slot.endTime}}</strong><div class="small muted">{{slot.dayOfWeek}}</div></div><div class="row"><button class="btn btn-secondary btn-sm" (click)="editSlot(slot)">Edit</button><button class="btn btn-danger btn-sm" (click)="deleteSlot(slot)">Deactivate</button></div></div>}@if (!slots.length) {<div class="small muted">No available slots returned for this date.</div>}</div></div></div>}
      }

      @if (tab === 'bookings') {<div class="card"><div class="row between"><div><h3 class="card-title">All lab bookings</h3><div class="card-sub">Operational view across students and labs.</div></div><button class="btn btn-secondary btn-sm" (click)="loadBookings()">Refresh</button></div><div class="divider"></div><div class="table-wrap"><table class="table"><thead><tr><th>Booking ID</th><th>Student</th><th>Lab</th><th>Date & time</th><th>Seat</th><th>Status</th></tr></thead><tbody>@for (booking of bookings; track booking.labBookingId) {<tr><td>{{booking.labBookingId}}</td><td><strong>{{booking.studentName || 'Student'}}</strong><div class="small muted">{{booking.studentIndexNumber || booking.studentId}}</div></td><td>{{booking.labName || booking.labId}}</td><td>{{booking.bookingDate|date:'mediumDate'}}<div class="small muted">{{booking.startTime}}–{{booking.endTime}}</div></td><td>{{booking.seatNumber || '—'}}</td><td><app-status-badge [value]="booking.status"/></td></tr>}</tbody></table></div></div>}

      @if (seatModal) {<div class="modal-backdrop" (click)="seatModal=false"><div class="modal" (click)="$event.stopPropagation()"><div class="modal-head"><h2>{{seatEditId ? 'Edit' : 'Add'}} seat</h2><button class="icon-btn" (click)="seatModal=false">×</button></div><form class="stack" #seatFormRef="ngForm" (ngSubmit)="saveSeat()"><div class="field"><label>Seat number</label><input class="input" required name="seat" [(ngModel)]="seatForm.seatNumber"></div>@if (seatEditId) {<label class="row"><input type="checkbox" name="active" [(ngModel)]="seatForm.isActive"> Active</label>}<div class="row"><button class="btn btn-primary" [disabled]="seatFormRef.invalid">Save</button><button type="button" class="btn btn-secondary" (click)="seatModal=false">Cancel</button></div></form></div></div>}
      @if (slotModal) {<div class="modal-backdrop" (click)="slotModal=false"><div class="modal" (click)="$event.stopPropagation()"><div class="modal-head"><h2>{{slotEditId ? 'Edit' : 'Add'}} time slot</h2><button class="icon-btn" (click)="slotModal=false">×</button></div><form class="form-grid" #slotFormRef="ngForm" (ngSubmit)="saveSlot()"><div class="field"><label>Day of week</label><select class="select" required name="day" [(ngModel)]="slotForm.dayOfWeek"><option>Monday</option><option>Tuesday</option><option>Wednesday</option><option>Thursday</option><option>Friday</option><option>Saturday</option><option>Sunday</option></select></div><div></div><div class="field"><label>Start time</label><input class="input" type="time" required name="start" [(ngModel)]="slotForm.startTime"></div><div class="field"><label>End time</label><input class="input" type="time" required name="end" [(ngModel)]="slotForm.endTime"></div>@if (slotEditId) {<label class="row"><input type="checkbox" name="active" [(ngModel)]="slotForm.isActive"> Active</label>}<div class="row"><button class="btn btn-primary" [disabled]="slotFormRef.invalid">Save</button><button type="button" class="btn btn-secondary" (click)="slotModal=false">Cancel</button></div></form></div></div>}
    </div>`
})
export class LabsAdminComponent implements OnInit {
  tab: 'labs' | 'bookings' = 'labs'; labs: Lab[] = []; selectedLab: Lab | null = null; seats: LabSeat[] = []; slots: LabSlot[] = []; bookings: LabBooking[] = [];
  labEditId: number | null = null; labForm: any = { code: '', name: '', labType: 'Computer', capacity: 30, isActive: true };
  seatModal = false; seatEditId: number | null = null; seatForm: any = { seatNumber: '', isActive: true };
  slotDate = new Date().toISOString().slice(0, 10); slotModal = false; slotEditId: number | null = null; slotForm: any = { dayOfWeek: 'Monday', startTime: '09:00', endTime: '10:00', isActive: true };
  constructor(private service: LabService, private errors: ApiErrorService, private toast: ToastService, private cdr: ChangeDetectorRef) {}
  ngOnInit() { this.loadLabs(); }
  loadLabs() { this.service.labs().subscribe({ next: labs => { this.labs = labs; this.cdr.markForCheck(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  editLab(lab: Lab) { this.labEditId = lab.labId; this.labForm = { code: lab.code, name: lab.name, labType: lab.labType, capacity: lab.capacity, isActive: lab.isActive }; }
  resetLab() { this.labEditId = null; this.labForm = { code: '', name: '', labType: 'Computer', capacity: 30, isActive: true }; }
  saveLab() { const request = this.labEditId ? this.service.updateLab(this.labEditId, this.labForm) : this.service.createLab({ code: this.labForm.code, name: this.labForm.name, labType: this.labForm.labType, capacity: this.labForm.capacity }); request.subscribe({ next: () => { this.toast.success('Lab saved.'); this.resetLab(); this.loadLabs(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  deleteLab(lab: Lab) { if (!confirm(`Delete ${lab.name}?`)) return; this.service.deleteLab(lab.labId).subscribe({ next: () => { this.toast.success('Lab deleted.'); this.selectedLab = this.selectedLab?.labId === lab.labId ? null : this.selectedLab; this.loadLabs(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  selectLab(lab: Lab) { this.selectedLab = lab; this.loadSeats(); this.loadSlots(); }
  loadSeats() { if (this.selectedLab) this.service.seats(this.selectedLab.labId).subscribe({ next: seats => { this.seats = seats; this.cdr.markForCheck(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  newSeat() { this.seatEditId = null; this.seatForm = { seatNumber: '', isActive: true }; this.seatModal = true; }
  editSeat(seat: LabSeat) { this.seatEditId = seat.labSeatId; this.seatForm = { seatNumber: seat.seatNumber, isActive: seat.isActive }; this.seatModal = true; }
  saveSeat() { if (!this.selectedLab) return; const request = this.seatEditId ? this.service.updateSeat(this.selectedLab.labId, this.seatEditId, this.seatForm) : this.service.createSeat(this.selectedLab.labId, { seatNumber: this.seatForm.seatNumber }); request.subscribe({ next: () => { this.seatModal = false; this.toast.success('Seat saved.'); this.loadSeats(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  deleteSeat(seat: LabSeat) { if (!this.selectedLab || !confirm(`Deactivate seat ${seat.seatNumber}?`)) return; this.service.deleteSeat(this.selectedLab.labId, seat.labSeatId).subscribe({ next: () => { this.toast.success('Seat deactivated.'); this.loadSeats(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  loadSlots() { if (this.selectedLab && this.slotDate) this.service.slots(this.selectedLab.labId, this.slotDate).subscribe({ next: slots => { this.slots = slots; this.cdr.markForCheck(); }, error: () => this.slots = [] }); }
  newSlot() { this.slotEditId = null; this.slotForm = { dayOfWeek: 'Monday', startTime: '09:00', endTime: '10:00', isActive: true }; this.slotModal = true; }
  editSlot(slot: LabSlot) { this.slotEditId = slot.labTimeSlotId; this.slotForm = { dayOfWeek: slot.dayOfWeek, startTime: slot.startTime.slice(0, 5), endTime: slot.endTime.slice(0, 5), isActive: slot.isActive }; this.slotModal = true; }
  saveSlot() { if (!this.selectedLab) return; const value = (time: string) => time.length === 5 ? `${time}:00` : time; const body = { dayOfWeek: this.slotForm.dayOfWeek, startTime: value(this.slotForm.startTime), endTime: value(this.slotForm.endTime), ...(this.slotEditId ? { isActive: this.slotForm.isActive } : {}) }; const request = this.slotEditId ? this.service.updateSlot(this.slotEditId, body) : this.service.createSlot(this.selectedLab.labId, body); request.subscribe({ next: () => { this.slotModal = false; this.toast.success('Time slot saved.'); this.loadSlots(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  deleteSlot(slot: LabSlot) { if (!confirm('Deactivate this time slot?')) return; this.service.deleteSlot(slot.labTimeSlotId).subscribe({ next: () => { this.toast.success('Time slot deactivated.'); this.loadSlots(); }, error: error => this.toast.error(this.errors.message(error)) }); }
  loadBookings() { this.service.allBookings().subscribe({ next: bookings => { this.bookings = bookings; this.cdr.markForCheck(); }, error: error => this.toast.error(this.errors.message(error)) }); }
}
