import { Injectable, signal } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { forkJoin, map, of, switchMap } from 'rxjs';
import { AdminDashboard, CertificateRequest, CertificateType, Complaint, ComplaintCategory, EventItem, EventRegistration, EventSeat, FeePayment, FeeReceipt, FeeType, Hostel, HostelApplication, HostelAvailability, Lab, LabBooking, LabSeat, LabSlot, NotificationItem, Room, StudentDashboard, SystemSetting, Venue } from '../models/domain.models';

const api=environment.apiUrl;

@Injectable({providedIn:'root'}) export class DashboardService{constructor(private h:HttpClient){} student(){return this.h.get<StudentDashboard>(`${api}/dashboard/student`)} admin(){return this.h.get<AdminDashboard>(`${api}/dashboard/admin`)}}

@Injectable({providedIn:'root'}) export class HostelService{
 constructor(private h:HttpClient){}
 hostels(){return this.h.get<Hostel[]>(`${api}/hostels`)} hostel(id:number){return this.h.get<Hostel>(`${api}/hostels/${id}`)} createHostel(b:unknown){return this.h.post<Hostel>(`${api}/hostels`,b)} updateHostel(id:number,b:unknown){return this.h.put(`${api}/hostels/${id}`,b)} deleteHostel(id:number){return this.h.delete(`${api}/hostels/${id}`)} availability(id:number,academicYear:string,semester:string){return this.h.get<HostelAvailability>(`${api}/hostels/${id}/availability`,{params:{academicYear,semester}})}
 rooms(hostelId?:number){return hostelId?this.h.get<Room[]>(`${api}/hostels/${hostelId}/rooms`):this.h.get<Room[]>(`${api}/rooms`)} createRoom(hostelId:number,b:unknown){return this.h.post<Room>(`${api}/hostels/${hostelId}/rooms`,b)} updateRoom(id:number,b:unknown){return this.h.put(`${api}/rooms/${id}`,b)} deleteRoom(id:number){return this.h.delete(`${api}/rooms/${id}`)} occupancy(id:number){return this.h.get<any>(`${api}/rooms/${id}/occupancy`)}
 apply(b:unknown){return this.h.post<HostelApplication>(`${api}/hostel-applications`,b)} mine(){return this.h.get<HostelApplication[]>(`${api}/hostel-applications/me`)} applications(status?:string,page=1){let p=new HttpParams().set('page',page);if(status)p=p.set('status',status);return this.h.get<HostelApplication[]>(`${api}/hostel-applications`,{params:p})} cancel(id:number){return this.h.delete(`${api}/hostel-applications/${id}`)} updateStatus(id:number,status:string){return this.h.put<HostelApplication>(`${api}/hostel-applications/${id}/status`,{status})} assignRoom(id:number,roomId:number){return this.h.put<HostelApplication>(`${api}/hostel-applications/${id}/assign-room`,{roomId})} unassignRoom(id:number){return this.h.put(`${api}/hostel-applications/${id}/unassign-room`,{})}
}

@Injectable({providedIn:'root'}) export class LabService{
 constructor(private h:HttpClient){}
 labs(){return this.h.get<Lab[]>(`${api}/labs`)} createLab(b:unknown){return this.h.post<Lab>(`${api}/labs`,b)} updateLab(id:number,b:unknown){return this.h.put(`${api}/labs/${id}`,b)} deleteLab(id:number){return this.h.delete(`${api}/labs/${id}`)}
 slots(labId:number,date:string){return this.h.get<LabSlot[]>(`${api}/labs/${labId}/slots`,{params:{date}})} createSlot(labId:number,b:unknown){return this.h.post<LabSlot>(`${api}/labs/${labId}/time-slots`,b)} updateSlot(id:number,b:unknown){return this.h.put(`${api}/lab-time-slots/${id}`,b)} deleteSlot(id:number){return this.h.delete(`${api}/lab-time-slots/${id}`)}
 seats(labId:number){return this.h.get<LabSeat[]>(`${api}/labs/${labId}/seats`)} availableSeats(labId:number,date:string,timeSlotId:number){return this.h.get<LabSeat[]>(`${api}/labs/${labId}/seats/availability`,{params:{date,timeSlotId}})} createSeat(labId:number,b:unknown){return this.h.post<LabSeat>(`${api}/labs/${labId}/seats`,b)} updateSeat(labId:number,id:number,b:unknown){return this.h.put(`${api}/labs/${labId}/seats/${id}`,b)} deleteSeat(labId:number,id:number){return this.h.delete(`${api}/labs/${labId}/seats/${id}`)}
 book(b:unknown){return this.h.post<LabBooking>(`${api}/lab-bookings`,b)} mine(){return this.h.get<LabBooking[]>(`${api}/lab-bookings/me`)} confirm(id:number){return this.h.put(`${api}/lab-bookings/${id}/confirm`,{})} cancel(id:number){return this.h.delete(`${api}/lab-bookings/${id}`)} allBookings(page=1){return this.h.get<LabBooking[]>(`${api}/lab-bookings`,{params:{page}})}
}

@Injectable({providedIn:'root'}) export class EventService{
 constructor(private h:HttpClient){}
 events(filters:Record<string,string|number|boolean|undefined>={}){let p=new HttpParams();Object.entries(filters).forEach(([k,v])=>{if(v!==undefined&&v!=='')p=p.set(k,String(v))});return this.h.get<EventItem[]>(`${api}/events`,{params:p})} event(id:number){return this.h.get<EventItem>(`${api}/events/${id}`)} createEvent(b:unknown){return this.h.post<EventItem>(`${api}/events`,b)} updateEvent(id:number,b:unknown){return this.h.put(`${api}/events/${id}`,b)} deleteEvent(id:number){return this.h.delete(`${api}/events/${id}`)}
 venues(){return this.h.get<Venue[]>(`${api}/venues`)} createVenue(b:unknown){return this.h.post<Venue>(`${api}/venues`,b)} updateVenue(id:number,b:unknown){return this.h.put(`${api}/venues/${id}`,b)} deleteVenue(id:number){return this.h.delete(`${api}/venues/${id}`)}
 seats(eventId:number){return this.h.get<EventSeat[]>(`${api}/events/${eventId}/seats`)} seatAvailability(eventId:number){return this.h.get<EventSeat[]>(`${api}/events/${eventId}/seats/availability`)} createSeat(eventId:number,b:unknown){return this.h.post<EventSeat>(`${api}/events/${eventId}/seats`,b)} updateSeat(id:number,b:unknown){return this.h.put(`${api}/event-seats/${id}`,b)} deleteSeat(id:number){return this.h.delete(`${api}/event-seats/${id}`)}
 register(eventId:number,eventSeatId?:number|null){return this.h.post<EventRegistration>(`${api}/event-registrations`,{eventId,eventSeatId:eventSeatId??null})} confirm(id:number){return this.h.put(`${api}/event-registrations/${id}/confirm`,{})} mine(){return this.h.get<EventRegistration[]>(`${api}/event-registrations/me`).pipe(switchMap(rows=>rows.length?forkJoin(rows.map(summary=>this.h.get<EventRegistration>(`${api}/event-registrations/${summary.eventRegistrationId}`).pipe(map(full=>({...full,startAt:summary.startAt,venueName:summary.venueName}))))):of([] as EventRegistration[])))} cancel(id:number){return this.h.delete(`${api}/event-registrations/${id}`)} registrations(filters:Record<string,string|number|undefined>={}){let p=new HttpParams();Object.entries(filters).forEach(([k,v])=>{if(v!==undefined&&v!=='')p=p.set(k,String(v))});return this.h.get<EventRegistration[]>(`${api}/event-registrations`,{params:p})}
}

@Injectable({providedIn:'root'}) export class ComplaintService{
 constructor(private h:HttpClient){} categories(){return this.h.get<ComplaintCategory[]>(`${api}/complaint-categories`)} createCategory(b:unknown){return this.h.post<ComplaintCategory>(`${api}/complaint-categories`,b)} updateCategory(id:number,b:unknown){return this.h.put<ComplaintCategory>(`${api}/complaint-categories/${id}`,b)} deleteCategory(id:number){return this.h.delete(`${api}/complaint-categories/${id}`)} create(b:unknown){return this.h.post<Complaint>(`${api}/complaints`,b)} mine(){return this.h.get<Complaint[]>(`${api}/complaints/me`)} all(filters:Record<string,string|number|undefined>={}){let p=new HttpParams();Object.entries(filters).forEach(([k,v])=>{if(v!==undefined&&v!=='')p=p.set(k,String(v))});return this.h.get<Complaint[]>(`${api}/complaints`,{params:p})} updateStatus(id:number,status:number,resolutionNote?:string){return this.h.put<Complaint>(`${api}/complaints/${id}/status`,{status,resolutionNote})}}

@Injectable({providedIn:'root'}) export class CertificateService{
 constructor(private h:HttpClient){} types(){return this.h.get<CertificateType[]>(`${api}/certificate-types`)} createType(b:unknown){return this.h.post<CertificateType>(`${api}/certificate-types`,b)} updateType(id:number,b:unknown){return this.h.put(`${api}/certificate-types/${id}`,b)} deleteType(id:number){return this.h.delete(`${api}/certificate-types/${id}`)} create(certificateTypeId:number,reason?:string){return this.h.post<CertificateRequest>(`${api}/certificate-requests`,{certificateTypeId,reason})} mine(){return this.h.get<CertificateRequest[]>(`${api}/certificate-requests/me`)} all(status?:string,page=1){let p=new HttpParams().set('page',page);if(status)p=p.set('status',status);return this.h.get<CertificateRequest[]>(`${api}/certificate-requests`,{params:p})} updateStatus(id:number,status:string,reviewNote?:string){return this.h.put<CertificateRequest>(`${api}/certificate-requests/${id}/status`,{status,reviewNote})}}

@Injectable({providedIn:'root'}) export class FeeService{
 constructor(private h:HttpClient){} types(){return this.h.get<FeeType[]>(`${api}/fees/types`)} createType(b:unknown){return this.h.post<FeeType>(`${api}/fees/types`,b)} updateType(id:number,b:unknown){return this.h.put(`${api}/fees/types/${id}`,b)} deleteType(id:number){return this.h.delete(`${api}/fees/types/${id}`)} mine(){return this.h.get<FeePayment[]>(`${api}/fees/me`)} unpaid(){return this.h.get<FeePayment[]>(`${api}/fees/me/unpaid`)} paid(){return this.h.get<FeePayment[]>(`${api}/fees/me/paid`)} pay(id:number){return this.h.post(`${api}/fees/${id}/simulate-payment`,{})} receipt(id:number){return this.h.get<FeeReceipt>(`${api}/fee-payments/${id}/receipt`)} all(){return this.h.get<FeePayment[]>(`${api}/fees`)} assign(b:unknown){return this.h.post(`${api}/fees/assign`,b)} updateStatus(id:number,status:string){return this.h.put(`${api}/fees/${id}/status`,{status})} delete(id:number){return this.h.delete(`${api}/fees/${id}`)} }

@Injectable({providedIn:'root'}) export class NotificationService{
 constructor(private h:HttpClient){} unread=signal(0); list(isRead?:boolean,page=1){let p=new HttpParams().set('page',page);if(isRead!==undefined)p=p.set('isRead',isRead);return this.h.get<NotificationItem[]>(`${api}/notifications/me`,{params:p})} refreshUnread(){this.h.get<number>(`${api}/notifications/me/unread-count`).subscribe({next:n=>this.unread.set(n),error:()=>this.unread.set(0)})} mark(id:number){return this.h.put(`${api}/notifications/${id}/read`,{})} markAll(){return this.h.put(`${api}/notifications/me/read-all`,{})}}

@Injectable({providedIn:'root'}) export class SettingsService{constructor(private h:HttpClient){} all(){return this.h.get<SystemSetting[]>(`${api}/admin/system-settings`)} update(key:string,settingValue:string){return this.h.put<SystemSetting>(`${api}/admin/system-settings/${encodeURIComponent(key)}`,{settingValue})} holdMinutes(){return this.h.get<{minutes:number}>(`${api}/admin/system-settings/reservation-hold-minutes`)} updateHold(minutes:number){return this.h.put<{minutes:number}>(`${api}/admin/system-settings/reservation-hold-minutes`,{minutes})}}
