import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LabService } from '../../core/services/portal-services';
import { AuthService } from '../../core/services/auth.service';
import { Lab, LabBooking, LabSeat, LabSlot } from '../../core/models/domain.models';
import { StatusBadgeComponent } from '../../shared/components/status-badge.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { ApiErrorService } from '../../core/services/api-error.service';
import { ToastService } from '../../core/services/toast.service';
import { TimeRangePipe } from '../../shared/pipes/time-range.pipe';
@Component({selector:'app-labs',standalone:true,imports:[CommonModule,FormsModule,StatusBadgeComponent,EmptyStateComponent,TimeRangePipe],template:`
<div class="page"><div class="page-head"><div><h1>Lab reservations</h1><p>Choose a lab, date, available time slot and seat. Double bookings are rejected by the API.</p></div></div>
<div class="grid grid-3"><div class="card" style="grid-column:span 1"><h3 class="card-title">1 · Choose lab</h3><div class="card-sub">Active labs available for reservation</div><div class="stack" style="margin-top:16px">@for(l of labs;track l.labId){<button class="btn" [class.btn-primary]="selectedLab?.labId===l.labId" [class.btn-secondary]="selectedLab?.labId!==l.labId" style="justify-content:flex-start;text-align:left" (click)="selectLab(l)"><span class="grow"><strong>{{l.code}} · {{l.name}}</strong><span class="small" style="display:block;opacity:.8">{{l.labType}} · {{l.capacity}} seats</span></span></button>}</div></div>
<div class="card" style="grid-column:span 2"><h3 class="card-title">2 · Pick date and slot</h3><div class="card-sub">Only slots valid for the selected date are returned.</div><div class="field" style="max-width:260px;margin-top:16px"><label>Booking date</label><input class="input" type="date" [min]="minDate" [(ngModel)]="date" (ngModelChange)="loadSlots()"></div>@if(selectedLab&&!date){<div class="empty">Choose a date to load available time slots.</div>}@if(slots.length){<div class="grid grid-3" style="margin-top:18px">@for(s of slots;track s.labTimeSlotId){<button class="card flat" style="text-align:left" [style.border-color]="selectedSlot?.labTimeSlotId===s.labTimeSlotId?'#6366f1':''" (click)="selectSlot(s)"><strong>{{s.startTime|timeRange:s.endTime}}</strong><div class="small muted">{{s.dayOfWeek}}</div></button>}</div>}@else if(selectedLab&&date&&!loadingSlots){<app-empty-state icon="⌘" title="No available slots" message="Try a different date or lab."/>}@if(loadingSlots){<div class="empty">Loading available slots…</div>}</div></div>
@if(selectedSlot){<div class="card" style="margin-top:18px"><div class="row between"><div><h3 class="card-title">3 · Select a seat</h3><div class="card-sub">Seat selection is optional if the lab does not expose seat records.</div></div><span class="badge info">{{selectedLab?.name}} · {{date}}</span></div><div class="divider"></div>@if(seats.length){<div class="row wrap">@for(s of seats;track s.labSeatId){<button class="btn btn-sm" [class.btn-primary]="selectedSeatId===s.labSeatId" [class.btn-secondary]="selectedSeatId!==s.labSeatId" (click)="selectedSeatId=s.labSeatId">{{s.seatNumber}}</button>}</div>}@else{<div class="alert info">No individual seat records were returned. You can book the slot without a seat.</div>}<div class="row" style="margin-top:18px"><button class="btn btn-primary" [disabled]="booking" (click)="book()">{{booking?'Creating reservation…':'Reserve this slot'}}</button></div></div>}
<div class="card" style="margin-top:18px"><div class="row between"><div><h3 class="card-title">My reservations</h3><div class="card-sub">Held, confirmed, cancelled and past reservations</div></div><button class="btn btn-secondary btn-sm" (click)="loadBookings()">Refresh</button></div><div class="divider"></div>@if(bookings.length){<div class="table-wrap"><table class="table"><thead><tr><th>Lab</th><th>Date & time</th><th>Seat</th><th>Status</th><th></th></tr></thead><tbody>@for(b of bookings;track b.labBookingId){<tr><td><strong>{{b.labName||('Lab #'+b.labId)}}</strong></td><td>{{b.bookingDate|date:'mediumDate'}}<div class="small muted">{{b.startTime|timeRange:b.endTime}}</div></td><td>{{b.seatNumber||'Auto / none'}}</td><td><app-status-badge [value]="b.status"/></td><td class="right"><div class="row" style="justify-content:flex-end">@if(b.status==='Held'){<button class="btn btn-success btn-sm" (click)="confirmBooking(b)">Confirm</button>}@if(b.status==='Held'||b.status==='Confirmed'){<button class="btn btn-danger btn-sm" (click)="cancelBooking(b)">Cancel</button>}</div></td></tr>}</tbody></table></div>}@else{<app-empty-state icon="⌘" title="No lab reservations" message="Your bookings will appear here."/>}</div></div>`})
export class LabsComponent implements OnInit{labs:Lab[]=[];bookings:LabBooking[]=[];selectedLab:Lab|null=null;slots:LabSlot[]=[];selectedSlot:LabSlot|null=null;seats:LabSeat[]=[];selectedSeatId:number|null=null;date='';minDate=new Date().toISOString().slice(0,10);loadingSlots=false;booking=false;constructor(private service:LabService,private auth:AuthService,private errors:ApiErrorService,private toast:ToastService){}ngOnInit(){this.service.labs().subscribe({next:x=>this.labs=x.filter(l=>l.isActive),error:e=>this.toast.error(this.errors.message(e))});this.loadBookings()}selectLab(l:Lab){this.selectedLab=l;this.selectedSlot=null;this.slots=[];this.seats=[];if(this.date)this.loadSlots()}loadSlots(){if(!this.selectedLab||!this.date)return;this.loadingSlots=true;this.selectedSlot=null;this.seats=[];this.service.slots(this.selectedLab.labId,this.date).subscribe({next:x=>{this.slots=x.filter(s=>s.isActive);this.loadingSlots=false},error:e=>{this.slots=[];this.loadingSlots=false;this.toast.error(this.errors.message(e))}})}selectSlot(s:LabSlot){this.selectedSlot=s;this.selectedSeatId=null;if(!this.selectedLab)return;this.service.availableSeats(this.selectedLab.labId,this.date,s.labTimeSlotId).subscribe({next:x=>this.seats=x,error:()=>this.seats=[]})}book(){if(!this.selectedLab||!this.selectedSlot||!this.date)return;this.booking=true;this.service.book({studentId:this.auth.studentId()||0,labId:this.selectedLab.labId,labTimeSlotId:this.selectedSlot.labTimeSlotId,labSeatId:this.selectedSeatId,bookingDate:this.date}).subscribe({next:()=>{this.booking=false;this.toast.success('Lab slot reserved. Confirm it before the hold expires.');this.loadSlots();this.loadBookings()},error:e=>{this.booking=false;this.toast.error(this.errors.message(e));this.loadSlots()}})}loadBookings(){this.service.mine().subscribe({next:x=>this.bookings=x,error:e=>this.toast.error(this.errors.message(e))})}confirmBooking(b:LabBooking){this.service.confirm(b.labBookingId).subscribe({next:()=>{this.toast.success('Reservation confirmed.');this.loadBookings()},error:e=>this.toast.error(this.errors.message(e))})}cancelBooking(b:LabBooking){if(!confirm('Cancel this lab reservation?'))return;this.service.cancel(b.labBookingId).subscribe({next:()=>{this.toast.success('Reservation cancelled.');this.loadBookings();if(this.selectedLab&&this.date)this.loadSlots()},error:e=>this.toast.error(this.errors.message(e))})}}
